### ISSUE TITLE
Questions about ViT end2end training

### ISSUE THREAD

**Issue by jialuli-luka** [cshizhe/VLN-HAMT#3]
Hi,
    When we only change the config to pretrain_r2r_e2e.json, and still run the main_r2r.py, it seems that the image files are not used. Besides, as described in the paper, ViT e2e training is done in the second stage. 
    Thus I train a model checkpoint that finishes first stage pretrain, and I directly use pretrain_r2r_e2e.json (also modify the ckpt path) and main_r2r_image.py to run the ViT e2e training. However, there's some dim mismatch error occurs in image_pretrain.py line 80 (which points to vilmodel.py line 550). Could you help check if there's anything I need to change?
    Thanks so much!

**Comment by cshizhe** [comment]
The main_r2r_image.py is used for e2e training.
Could you show what the problem is?

**Comment by jialuli-luka** [comment]
The specific error message is: 

Traceback (most recent call last):
  File "pretrain_src/main_r2r_image.py", line 586, in <module>
    main(opts)
  File "pretrain_src/main_r2r_image.py", line 249, in main
    loss = model(batch, task=task, compute_loss=True)
  File "/playpen/jialu/python3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/playpen/jialu/python3/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 619, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/playpen/jialu/python3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/playpen/jialu/VLN-pretraining/pretrain_src/model/image_pretrain.py", line 80, in forward
    batch['hist_mrc_masks'], batch['hist_img_probs'], compute_loss)
  File "/playpen/jialu/VLN-pretraining/pretrain_src/model/image_pretrain.py", line 175, in forward_mrc
    None, None, None, None, hist_mrc_masks=hist_mrc_masks)
  File "/playpen/jialu/python3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/playpen/jialu/VLN-pretraining/pretrain_src/model/image_vilmodel.py", line 92, in forward
    batch_size=batch_size)
  File "/playpen/jialu/python3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/playpen/jialu/VLN-pretraining/pretrain_src/model/vilmodel.py", line 550, in forward
    self.ang_layer_norm(self.ang_linear(ang_feats)) + \
  File "/playpen/jialu/python3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/playpen/jialu/python3/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "/playpen/jialu/python3/lib/python3.6/site-packages/torch/nn/functional.py", line 1692, in linear
    output = input.matmul(weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0

**Comment by cshizhe** [comment]
Do you check the feature dimension? Our work employs ViT with 768 hidden size that is pretrained on Imagenet.

**Comment by jialuli-luka** [comment]
Thanks! It should be the case that I use different ViT features.
